spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(AQtxcS8+4EroDjVap5LDVxVU0w33WZqJ8X+NSjqHKQp9FLAsAIkAiVYjqrskK+MB)
    username: ENC(9wPt5xIo2wXQkG7fXfpX9g==)
    password: ENC(VoUGAjjXs08a/tJfOHT1sg==)

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
