set FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE address;
TRUNCATE TABLE member;
TRUNCATE TABLE post;
TRUNCATE TABLE enroll;
TRUNCATE TABLE post_comment;
TRUNCATE TABLE notification;
TRUNCATE TABLE member_evaluation;
set FOREIGN_KEY_CHECKS = 1;